website_home_index:
    path:     /
    defaults: { _controller: WebsiteBundle:Home:index }

website_store_index:
    path:     /store
    defaults: { _controller: WebsiteBundle:Store:index }

website_store_charge:
    path:     /store-charge
    defaults: { _controller: WebsiteBundle:Store:charge}
    methods:   POST