cpanel:
    resource: "@CpanelBundle/Resources/config/routing.yml"
    prefix:   /cpanel

website:
    resource: "@WebsiteBundle/Resources/config/routing.yml"
    prefix:   /
#    prefix:   /{_locale}/
#    requirements:
#        _locale: '%app.locales%'

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"